### PR TITLE
Add Go playground with Go client as of v3.0.0-beta01

### PR DESCRIPTION
**Pull request by aseure**

### CODE REVIEW

**Comment by aseure** [comment]
Maybe we should migrate those `setup/` documents then? https://github.com/algolia/doc-api-clients-squad/tree/master/setup

WDYT? Should we keep everything there or move them here? I'd rather not keep them in two different places.

**Comment by nunomaduro** [comment]
I think those setup documents, should be migrated to a README.md in each playground @aseure. Afterwords we can remove them.

**Comment by aseure** [comment]
@nunomaduro I agree. Let's do this! I'll start with the Go setup today or tomorrow :) Thanks

**Comment by aseure** [comment]
@nunomaduro I've added the README.md. Feel free to approve/merge whenever you want :)

**Pull request merged**
